---
abstract: 'Output your benchmarks as test diagnostics'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Benchmark
provides:
  App::Benchmark:
    file: lib/App/Benchmark.pm
    version: 1.100870
requires:
  Benchmark: 0
  Capture::Tiny: 0
  Carp: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-Benchmark
  homepage: http://search.cpan.org/dist/App-Benchmark/
  repository: http://github.com/hanekomu/App-Benchmark
version: 1.100870
