---
abstract: 'Output your benchmarks as test diagnostics'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Benchmark
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Benchmark: 0
  IO::Capture::Stdout: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-Benchmark
  homepage: http://search.cpan.org/dist/App-Benchmark/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/app-benchmark.git
version: 0.04
